version: '2'

services:
  fuse-box: 
    image: mhart/alpine-node:7.8.0
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "npm install && sh fix-fuse-box.sh && npm run watch"